//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Kho.Model
{
    using QL_Kho.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Account:BaseViewModel
    {
        private int _Id;
        public int Id
        {
            get
            {
                return _Id;
            }
            set
            {
                _Id = value;
                OnPropertyChanged();
            }
        }

        private string _DisplayName;
        public string DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                _DisplayName = value;
                OnPropertyChanged();
            }
        }

        private string _UserName;
        public string UserName 
        {
            get
            {
                return _UserName;
            }
            set
            {
                _UserName = value;
                OnPropertyChanged();
            }
        }

        private string _Password;
        public string Password 
        {
            get
            {
                return _Password;
            }
            set
            {
                _Password = value;
                OnPropertyChanged();
            }
        }

        private int _IdRole;
        public int IdRole
        {
            get
            {
                return _IdRole;
            }
            set
            {
                _IdRole = value;
                OnPropertyChanged();
            }
        }
    
        private AccountRole _AccountRole;
        public virtual AccountRole AccountRole
        {
            get
            {
                return _AccountRole;
            }
            set
            {
                _AccountRole = value;
                OnPropertyChanged();
            }
        }
    }
}
